# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logPage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
